Repository farmsystem-summer-project-team9/Akoclub, pull requests merged in 2025-08, with the labels that each got.

#13 [feat]/#12-결과 방식 선택 페이지 구현
  static/css/questionStyle.css
  static/images/엎드린아코.png
  static/js/score.js
  templates/index.html
  templates/result_choice.html
Labels: frontend, feat, yuna

#17 [feat]/#16 - 체육 분과 세부 질문 구현
  static/js/detailQuestions.js
  static/js/questionData.js
  static/js/score.js
  templates/detail_questions/sports/sports_dQ1.html
  templates/detail_questions/sports/sports_dQ2.html
  templates/detail_questions/sports/sports_dQ3.html
  templates/detail_questions/sports/sports_dQ4.html
Labels: frontend, feat, yuna

#23 [feat] #18 - 동아리 DB 생성 밎 Flask와 연결
  .github/CODEOWNERS
  app.py
  clubs.csv
  csvjson.json
Labels: heewon, backend, feat

#29 [Refactor]/#28 - ui 및 레이아웃 개선
  app/templates/detail_questions/art/art_dQ1.html
  app/templates/detail_questions/art/art_dQ2.html
  app/templates/detail_questions/art/art_dQ3.html
  app/templates/detail_questions/art/art_dQ4.html
  app/templates/detail_questions/performance/performance_dQ1.html
  app/templates/detail_questions/performance/performance_dQ2.html
  app/templates/detail_questions/performance/performance_dQ3.html
  app/templates/detail_questions/performance/performance_dQ4.html
  app/templates/detail_questions/performance/performance_dQ5.html
  app/templates/detail_questions/social/social_dQ1.html
  app/templates/detail_questions/social/social_dQ2.html
  app/templates/detail_questions/social/social_dQ3.html
  app/templates/detail_questions/sports/sports_dQ1.html
  app/templates/detail_questions/sports/sports_dQ2.html
  app/templates/detail_questions/sports/sports_dQ3.html
  app/templates/detail_questions/sports/sports_dQ4.html
  app/templates/detail_questions/study/study_dQ1.html
  app/templates/detail_questions/study/study_dQ2.html
  app/templates/detail_questions/study/study_dQ3.html
  app/templates/detail_questions/study/study_dQ4.html
  app/templates/detail_questions/study/study_dQ5.html
  app/templates/detail_questions/volunteer/volunteer_dQ1.html
  app/templates/detail_questions/volunteer/volunteer_dQ2.html
  app/templates/detail_questions/volunteer/volunteer_dQ3.html
  app/templates/index.html
  app/templates/questions/question_1.html
  static/css/indexStyle.css
  static/css/questionStyle.css
  static/css/resultStyle.css
Labels: frontend, wongyu

#33 feat/#30 - 해당 분과 전체 동아리 조회 기능 구현
  app/routes/__pycache__/__init__.cpython-313.pyc
  app/routes/__pycache__/department.cpython-312.pyc
  app/routes/__pycache__/department.cpython-313.pyc
  app/routes/__pycache__/main.cpython-312.pyc
  app/routes/__pycache__/main.cpython-313.pyc
  app/routes/main.py
  app/templates/club_detail.html
  app/templates/club_list.html
  app/templates/clubs.html
  static/css/clubDetailStyle.css
  static/css/clubListStyle.css
Labels: frontend, feat, yuna

#38 [Fix/#36] - 동아리 오류 수정
  app/constants/__pycache__/club_mapping.cpython-312.pyc
  app/constants/club_mapping.py
  app/routes/__pycache__/main.cpython-312.pyc
  app/routes/main.py
  app/templates/detail_questions/performance/performance_dQ5.html
  app/templates/detail_questions/social/social_dQ3.html
  app/templates/detail_questions/sports/sports_dQ4.html
  app/templates/detail_questions/study/study_dQ3.html
  app/templates/detail_questions/volunteer/volunteer_dQ3.html
  app/templates/result.html
  static/css/resultStyle.css
Labels: frontend, feat, yuna

#39 [feat] #37 - 동아리 검색 API 생성
  app/__init__.py
  app/routes/search.py
Labels: backend, feat, yoonki
